### ISSUE TITLE
Submit Zig syntax highlighter upstream

### ISSUE THREAD

**Issue by abhin4v** [ElementW/kate-highlight-zig#2]
Please submit the Zig highlighting file upstream to https://github.com/KDE/syntax-highlighting so that every project downstream from it can take advantage of your work.

**Comment by ElementW** [comment]
1. KDE doesn't use GitHub as their upstream git host.
2. It's not up to date with the latest versions of Zig, at all.
3. [No.](https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/98)

**Comment by abhin4v** [comment]
Thank you.
